import type { Lang } from "../i18n";

const en = {
  kitchen: "Our kitchen",
  flavors: "The flavors",
  jars: "The jars",
  table: "At your table",
  explore: "Explore the jars",
  eyebrow: "A little something from きみえ’s kitchen",
  hero: ["Small jars.", "Lovely possibilities."],
  intro:
    "Whole-grain mustard. Rich olive tapenade. A little care, a little character, and a whole new way to enjoy the everyday.",
  caption: "Made for the meals you make your own.",
  kitchenCaption: "A moment in きみえ’s kitchen",
  quiet: [
    "Good food doesn’t have to be complicated.",
    "Sometimes, it just needs a spoonful.",
  ],
  flavorHeading: ["Small ingredients.", "A world of flavor."],
  mustard: "Whole-grain mustard",
  tapenade: "Olive tapenade",
  mustardNote: "Bright. Tangy. A little unexpected.",
  tapenadeNote: "Deep. Savory. Beautifully bold.",
  mustardDesc:
    "The gentle pop of mustard seeds. A touch of honey. Enough brightness to wake up the simplest plate.",
  tapenadeDesc:
    "Black olives, capers, and anchovies. A generous, savory spoonful that belongs on warm bread and much more.",
  sceneNote: "A closer look at the flavors",
  nextJar: "Meet this jar",
  two: ["Two personalities.", "One place at your table."],
  twoDesc:
    "Start with the flavor that speaks to you. There’s a little possibility in every jar.",
  ingredients: "Ingredients & details",
  selected: "Your chosen flavor",
  choose: "Choose this flavor",
  mealTitle: ["Your everyday.", "With a little extra."],
  mealIntro:
    "A salad for lunch. A slow supper. Something golden from the oven. Make it yours.",
  meals: ["Something fresh", "Something comforting", "Something golden"],
  mealNames: [
    "A brighter bowl of greens.",
    "A little twist on pasta night.",
    "The side that steals the show.",
  ],
  mealDescs: [
    "A spoonful of mustard brings a bright, tangy finish to crisp vegetables.",
    "Bring the character of mustard to a simple bowl of pasta.",
    "Pair warm potatoes with the gentle heat and texture of whole-grain mustard.",
  ],
  pairing: "Pairs with whole-grain mustard",
  makerTitle: ["A kitchen. A little care.", "A jar worth sharing."],
  makerIntro:
    "Good flavor begins with attention. Choosing ingredients, finding their balance, and taking care of the little things along the way.",
  close: ["Make the ordinary", "a little lovely."],
  closeText: "There’s a place for a little more flavor at your table.",
  original: "View original page",
  back: "Back to top",
  language: "Language",
  menu: "Menu",
  motion: "Motion",
  motionOn: "On",
  motionOff: "Off",
  serving: "Serving inspiration",
};
type Copy = typeof en;
export const storyCopy: Record<Lang, Copy> = {
  en,
  ja: {
    kitchen: "きみえの台所",
    flavors: "味わい",
    jars: "ふたつの瓶",
    table: "食卓へ",
    explore: "瓶詰めを見る",
    eyebrow: "きみえの台所から、ひとさじの贈りもの",
    hero: ["小さな瓶に、", "おいしい可能性。"],
    intro:
      "粒マスタードと、濃厚なタプナード。ひとさじの工夫が、いつものごはんを少し特別に。",
    caption: "いつもの料理を、あなたらしい一皿に。",
    kitchenCaption: "きみえの台所のひととき",
    quiet: ["おいしさは、むずかしくない。", "ひとさじで、変わることがある。"],
    flavorHeading: ["小さな素材に、", "豊かな味わい。"],
    mustard: "粒マスタード",
    tapenade: "オリーブのタプナード",
    mustardNote: "爽やかに、つぶつぶと。",
    tapenadeNote: "濃厚で、奥深い旨味。",
    mustardDesc:
      "マスタードの粒がはじけ、はちみつがやさしく香る。いつもの一皿に、心地よいアクセント。",
    tapenadeDesc:
      "ブラックオリーブ、ケッパー、アンチョビ。温かなパンにもよく合う、旨味豊かなひとさじ。",
    sceneNote: "味わいを、少し近くで",
    nextJar: "この瓶を見る",
    two: ["ふたつの個性。", "あなたの食卓に。"],
    twoDesc: "気になる味から、ひと瓶。新しいおいしさを見つけてください。",
    ingredients: "原材料と詳細",
    selected: "選んだ味わい",
    choose: "この味を選ぶ",
    mealTitle: ["いつもの食卓に、", "小さなひと工夫。"],
    mealIntro:
      "お昼のサラダ、ゆっくり楽しむ夕食、焼きたてのじゃがいも。あなたらしく楽しんで。",
    meals: ["さっぱりと", "ほっとする一皿", "こんがりと"],
    mealNames: [
      "野菜のおいしさを、鮮やかに。",
      "いつものパスタに、ひと工夫。",
      "付け合わせが、主役になる。",
    ],
    mealDescs: [
      "粒マスタードの爽やかな酸味が、野菜のおいしさを引き立てます。",
      "シンプルなパスタに、マスタードの個性を添えて。",
      "温かなじゃがいもに、粒マスタードの食感とやさしい辛味を。",
    ],
    pairing: "粒マスタードと一緒に",
    makerTitle: ["台所から、心を込めて。", "分け合いたくなる、ひと瓶。"],
    makerIntro:
      "素材を選び、味のバランスを整え、小さなことにも気を配る。そんな積み重ねから、おいしさは生まれます。",
    close: ["いつもの日を、", "少し、おいしく。"],
    closeText: "あなたの食卓にも、ひとさじの楽しみを。",
    original: "元のページを見る",
    back: "ページの先頭へ",
    language: "言語",
    menu: "メニュー",
    motion: "動き",
    motionOn: "オン",
    motionOff: "オフ",
    serving: "食卓のアイデア",
  },
  fr: {
    kitchen: "Notre cuisine",
    flavors: "Les saveurs",
    jars: "Les bocaux",
    table: "À votre table",
    explore: "Découvrir les bocaux",
    eyebrow: "Une petite attention de la cuisine de きみえ",
    hero: ["Petits bocaux.", "Belles possibilités."],
    intro:
      "Moutarde en grains et tapenade généreuse. Un peu de soin, du caractère, et une nouvelle façon de savourer le quotidien.",
    caption: "Pour les repas qui vous ressemblent.",
    kitchenCaption: "Un instant dans la cuisine de きみえ",
    quiet: [
      "Bien manger peut être tout simple.",
      "Parfois, une cuillerée suffit.",
    ],
    flavorHeading: ["De petits ingrédients.", "Tout un monde de saveurs."],
    mustard: "Moutarde en grains",
    tapenade: "Tapenade d’olives",
    mustardNote: "Vive. Acidulée. Un peu inattendue.",
    tapenadeNote: "Profonde. Savoureuse. Généreuse.",
    mustardDesc:
      "Le croquant des graines, une touche de miel. Juste ce qu’il faut de fraîcheur pour réveiller une assiette.",
    tapenadeDesc:
      "Olives noires, câpres et anchois. Une cuillerée riche en goût, parfaite sur du pain chaud et bien plus.",
    sceneNote: "Les saveurs, de plus près",
    nextJar: "Découvrir ce bocal",
    two: ["Deux caractères.", "Une place à votre table."],
    twoDesc:
      "Commencez par la saveur qui vous attire. Chaque bocal ouvre de nouvelles possibilités.",
    ingredients: "Ingrédients et détails",
    selected: "Votre saveur choisie",
    choose: "Choisir cette saveur",
    mealTitle: ["Le quotidien.", "Avec un petit supplément."],
    mealIntro:
      "Une salade, un dîner tranquille, un plat doré au four. À vous de jouer.",
    meals: ["De la fraîcheur", "Du réconfort", "Une touche dorée"],
    mealNames: [
      "Une salade plus vive.",
      "Une nouvelle idée pour les pâtes.",
      "Un accompagnement qui attire tous les regards.",
    ],
    mealDescs: [
      "La moutarde apporte une note vive et acidulée aux légumes croquants.",
      "Invitez le caractère de la moutarde dans un simple plat de pâtes.",
      "Accompagnez les pommes de terre chaudes de moutarde en grains.",
    ],
    pairing: "Avec la moutarde en grains",
    makerTitle: ["Une cuisine. De l’attention.", "Un bocal à partager."],
    makerIntro:
      "Choisir les ingrédients, équilibrer les saveurs, soigner les petits détails. Le goût commence par l’attention.",
    close: ["Rendre le quotidien", "un peu plus délicieux."],
    closeText: "Une place pour un peu plus de saveur à votre table.",
    original: "Voir la page originale",
    back: "Retour en haut",
    language: "Langue",
    menu: "Menu",
    motion: "Animation",
    motionOn: "Oui",
    motionOff: "Non",
    serving: "Idées à servir",
  },
  zh: {
    kitchen: "我们的厨房",
    flavors: "风味",
    jars: "两款瓶装酱",
    table: "上桌灵感",
    explore: "探索瓶装酱",
    eyebrow: "来自 きみえ 厨房的一点心意",
    hero: ["小小一瓶，", "满满的可能。"],
    intro: "颗粒芥末，浓郁橄榄酱。一点用心，一点个性，让日常餐桌多一份惊喜。",
    caption: "为你亲手做的每一餐。",
    kitchenCaption: "きみえ 厨房的一刻",
    quiet: ["美味，不必复杂。", "有时，只需要一勺。"],
    flavorHeading: ["小小食材，", "丰富滋味。"],
    mustard: "颗粒芥末酱",
    tapenade: "橄榄酱",
    mustardNote: "清爽、酸香，有一点惊喜。",
    tapenadeNote: "浓郁、咸鲜，层次丰富。",
    mustardDesc: "芥末籽的弹脆，蜂蜜的温柔。为最简单的一盘菜，添上清新滋味。",
    tapenadeDesc:
      "黑橄榄、酸豆与鳀鱼。一勺丰富咸香，配温热面包或更多家常料理。",
    sceneNote: "靠近一点，认识风味",
    nextJar: "认识这瓶酱",
    two: ["两种个性，", "同在你的餐桌。"],
    twoDesc: "从喜欢的风味开始，每一瓶都有新可能。",
    ingredients: "原料与详情",
    selected: "你选择的风味",
    choose: "选择这款风味",
    mealTitle: ["日常一餐，", "多一点美好。"],
    mealIntro: "午间沙拉、悠闲晚餐、烤箱里的金黄。做成你喜欢的模样。",
    meals: ["一份清爽", "一份温暖", "一抹金黄"],
    mealNames: [
      "让蔬菜更有滋味。",
      "为意面之夜添点新意。",
      "配菜也能成为主角。",
    ],
    mealDescs: [
      "一勺芥末，为脆嫩蔬菜带来清爽酸香。",
      "让芥末的个性走进简单的一碗意面。",
      "温热土豆搭配颗粒芥末的温和辛香与口感。",
    ],
    pairing: "搭配颗粒芥末酱",
    makerTitle: ["一间厨房，一份用心。", "一瓶值得分享的滋味。"],
    makerIntro: "挑选食材、平衡风味、照顾每个细节。好味道来自一点一滴的用心。",
    close: ["让平常的日子，", "多一点美味。"],
    closeText: "为你的餐桌，添一勺快乐。",
    original: "查看原始页面",
    back: "回到顶部",
    language: "语言",
    menu: "菜单",
    motion: "动态效果",
    motionOn: "开",
    motionOff: "关",
    serving: "上桌灵感",
  },
  "zh-TW": {
    kitchen: "我們的廚房",
    flavors: "風味",
    jars: "兩款瓶裝醬",
    table: "上桌靈感",
    explore: "探索瓶裝醬",
    eyebrow: "來自 きみえ 廚房的一點心意",
    hero: ["小小一瓶，", "滿滿的可能。"],
    intro: "顆粒芥末，濃郁橄欖醬。一點用心，一點個性，讓日常餐桌多一份驚喜。",
    caption: "為你親手做的每一餐。",
    kitchenCaption: "きみえ 廚房的一刻",
    quiet: ["美味，不必複雜。", "有時，只需要一匙。"],
    flavorHeading: ["小小食材，", "豐富滋味。"],
    mustard: "顆粒芥末醬",
    tapenade: "橄欖醬",
    mustardNote: "清爽、酸香，有一點驚喜。",
    tapenadeNote: "濃郁、鹹鮮，層次豐富。",
    mustardDesc: "芥末籽的彈脆，蜂蜜的溫柔。為最簡單的一盤菜，添上清新滋味。",
    tapenadeDesc:
      "黑橄欖、酸豆與鯷魚。一匙豐富鹹香，配溫熱麵包或更多家常料理。",
    sceneNote: "靠近一點，認識風味",
    nextJar: "認識這瓶醬",
    two: ["兩種個性，", "同在你的餐桌。"],
    twoDesc: "從喜歡的風味開始，每一瓶都有新可能。",
    ingredients: "原料與詳情",
    selected: "你選擇的風味",
    choose: "選擇這款風味",
    mealTitle: ["日常一餐，", "多一點美好。"],
    mealIntro: "午間沙拉、悠閒晚餐、烤箱裡的金黃。做成你喜歡的模樣。",
    meals: ["一份清爽", "一份溫暖", "一抹金黃"],
    mealNames: [
      "讓蔬菜更有滋味。",
      "為義大利麵之夜添點新意。",
      "配菜也能成為主角。",
    ],
    mealDescs: [
      "一匙芥末，為脆嫩蔬菜帶來清爽酸香。",
      "讓芥末的個性走進簡單的一碗義大利麵。",
      "溫熱馬鈴薯搭配顆粒芥末的溫和辛香與口感。",
    ],
    pairing: "搭配顆粒芥末醬",
    makerTitle: ["一間廚房，一份用心。", "一瓶值得分享的滋味。"],
    makerIntro: "挑選食材、平衡風味、照顧每個細節。好味道來自一點一滴的用心。",
    close: ["讓平常的日子，", "多一點美味。"],
    closeText: "為你的餐桌，添一匙快樂。",
    original: "查看原始頁面",
    back: "回到頂部",
    language: "語言",
    menu: "選單",
    motion: "動態效果",
    motionOn: "開",
    motionOff: "關",
    serving: "上桌靈感",
  },
};
